import './css/globals.css';
import './css/utility-patterns.css';
import './css/styles.css';

import { Inter } from 'next/font/google';
import Theme from './theme-provider';
import AppProvider from './app-provider';
import { ClerkProvider } from '@clerk/nextjs';
import { Providers } from './providers';
import CustomEditor from '../components/CustomEditor';
import ChatThemeProvider from '@/components/chat/theme-provider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
        <body
          className={`${inter.variable} font-inter antialiased bg-neutral-200 dark:bg-blue-800 text-slate-600 dark:text-slate-300 no-scrollbar`}
        >
          <Theme>
            <AppProvider>
              <Providers>{children}</Providers>
            </AppProvider>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
