export const motivationQuotes = [
  'Things work out best for those who make the best of how things work out.',
  'If you are not willing to risk the usual you will have to settle for the ordinary.',
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  'What you get by achieving your goals is not as important as what you become by achieving your goals.',
  'All our dreams can come true if we have the courage to pursue them.',
  'If you do what you always did, you will get what you always got.',
  'Success is walking from failure to failure with no loss of enthusiasm.',
  'Magic is believing in yourself. If you can make that happen, you can make anything happen.',
  'No matter how far life pushes you down, no matter how much you hurt, you can always bounce back.',
  'Drown out the doubt around you by repeating your future plans and achievements to yourself daily.',
  'You must train your intuition: you must trust the small voice inside you which tells you exactly what to say, what to decide.',
  'Look forward with hope, not backwards with regret.',
  'If something is important enough, even if the odds are against you, you should still do it.',
  "We don't even know how strong we are until we are forced to bring that hidden strength forward.",
  'There is nothing wrong with dreaming, but there is everything wrong with dreaming without any intention to make the dream a reality.',
  'The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.-Eleanor Roosevelt.',
  'Today start your day with a smile, calmness of mind, coolness of emotions and a heart filled with gratitude.',
  'Get enough sleep every night. An exhausted mind is rarely productive.',
  "When your motivation needs a break, it's up to your dedication to keep you on track.",
  'Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.',
  "I have not failed. I've just found 10,000 ways that won't work.",
  'Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.',
  'Try not to become a person of success, but rather try to become a person of value.',
  "If you don't value your time, neither will others. Stop giving away your time and talents - start charging for it.",
  'No one can make you feel inferior without your consent.',
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
  "Don't raise your voice, improve your argument.",
  'The meaning of life is to find your gift. The purpose of life is to give it away.',
  'When you stop chasing the wrong things, you give the right things a chance to catch you.',
  "Don't be afraid to give up the good to go for the great.",
  'No masterpiece was ever created by a lazy artist.',
  'Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.',
  "If you can't explain it simply, you don't understand it well enough.",
  'Blessed are those who can give without remembering and take without forgetting.',
  "What's the point of being alive if you don't at least try to do something remarkable.",
  'Life is not about finding yourself. Life is about creating yourself.',
  'What seems to us as bitter trials are often blessings in disguise.',
  'Nothing in the world is more common than unsuccessful people with talent.',
  'Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.',
  "Your problem isn't the problem. Your reaction is the problem.",
  'You can do anything, but not everything.',
  'Do what you can with all you have, wherever you are.',
  'Good things come to people who wait, but better things come to those who go out and get them.',
  "You don't have to be great to start, but you have to start to be great.",
  'Doubt kills more dreams than failure ever will.',
  'Hardships often prepare ordinary people for an extraordinary destiny.',
  "Believe you can and you're halfway there.",
  "Your limitation: it's only your imagination.",
  'Push yourself, because no one else is going to do it for you.',
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  'Wake up with determination. Go to bed with satisfaction.',
  "Don't wait for opportunity. Create it.",
  'Sometimes we can only find our true direction when we let the wind of change carry us.',
];
