export const motivationQuotes = [
  'If you want to achieve greatness stop asking for permission.',
  'Things work out best for those who make the best of how things work out.',
  'To live a creative life, we must lose our fear of being wrong.',
  'If you are not willing to risk the usual you will have to settle for the ordinary.',
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  'All our dreams can come true if we have the courage to pursue them.',
  'Good things come to people who wait, but better things come to those who go out and get them.',
  'If you do what you always did, you will get what you always got.',
  'Success is walking from failure to failure with no loss of enthusiasm.',
  'Just when the caterpillar thought the world was ending, he turned into a butterfly.',
  'Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.',
  "Opportunities don't happen, you create them.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  'Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.',
  'Try not to become a person of success, but rather try to become a person of value.',
  "If you don't value your time, neither will others. Stop giving away your time and talents - start charging for it.",
  'No one can make you feel inferior without your consent.',
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
  "Don't raise your voice, improve your argument.",
  'The meaning of life is to find your gift. The purpose of life is to give it away.',
  'The distance between insanity and genius is measured only by success.',
  'When you stop chasing the wrong things, you give the right things a chance to catch you.',
  "Don't be afraid to give up the good to go for the great.",
  'No masterpiece was ever created by a lazy artist.',
  'Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.',
  "If you can't explain it simply, you don't understand it well enough.",
  'Blessed are those who can give without remembering and take without forgetting.',
  "What's the point of being alive if you don't at least try to do something remarkable.",
  'Life is not about finding yourself. Life is about creating yourself.',
  'What seems to us as bitter trials are often blessings in disguise.',
  'Nothing in the world is more common than unsuccessful people with talent.',
  'Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.',
  "Your problem isn't the problem. Your reaction is the problem.",
  'You can do anything, but not everything.',
];
